### ISSUE TITLE
config not generated for asterisk domain

### ISSUE THREAD

**Issue by sandrodz** [JrCs/docker-letsencrypt-nginx-proxy-companion#561]
<img width="524" alt="Screen Shot 2019-07-27 at 8 09 59 PM" src="https://user-images.githubusercontent.com/8479569/62003573-fee97900-b129-11e9-82ea-9cc2fec7f4eb.png">

**Comment by buchdag** [comment]
Hi, thanks for reporting this, I'm working on it.

**Comment by buchdag** [comment]
Can you pull and try `duch/letsencrypt-nginx-proxy-companion:561` to see if the fix work for you ?

If yes I'll make a PR and merge this branch.

I made the location configuration work as follow. Let say the domain is `foo.bar.baz.example.tld`:

- if a config file with the exact same name as your domain (`foo.bar.baz.example.tld`) is present, use it.
- else try every corresponding wildcard domain, from most qualified to least qualified, first ascending through the labels to the base domain (`*.bar.baz.example.tld`, `*.baz.example.tld`, `*.example.tld`) then descending (`foo.bar.baz.example.*`, `foor.bar.baz.*`, `foo.bar.*`, `foo.*`). The first that match an existing config file will be used.
- if no wildcard location config file was found either, use the `default` location config file.

**Comment by buchdag** [comment]
ping @sandrodz

**Comment by sandrodz** [comment]
Hey, I'm at loss, how would I test this? I cannot find this image: `duch/letsencrypt-nginx-proxy-companion:561`

**Comment by buchdag** [comment]
Sorry, last week push seem to have failed without me noticing it.

I pushed the image again, it's now available : https://cloud.docker.com/repository/docker/duch/letsencrypt-nginx-proxy-companion/tags

**Comment by smartens** [comment]
I also need some guidance for this. I trying to get gitlab pages working. I tried your image but it still doesn't work. Here is my docker compose file:

If you need any logs, please let me know.

```
version: '3'

networks:
  nginx_default:
    external: true
    
volumes:
  config:
  logs:
  data:

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    #hostname: git.team.softec.uni-due.de
    networks:
      - nginx_default
    environment:
      VIRTUAL_HOST: git.team.softec.uni-due.de,*.pages.team.softec.uni-due.de
      LETSENCRYPT_HOST: git.team.softec.uni-due.de,*.pages.team.softec.uni-due.de
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.team.softec.uni-due.de'
        letsencrypt['enabled'] = false # disable because nginx-proxy-letsencrypt is handling the certificates
        gitlab_pages['enable'] = true
        pages_external_url 'http://pages.team.softec.uni-due.de'
          
    ulimits: # from https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1350, still warnings because gitlab cannot change them in the container but parameters should be sound
      sigpending: 62793
      nproc: 131072
      nofile: 60000
      core: 0
    expose:
      - 80
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
```

**Comment by buchdag** [comment]
@smartens This is a different issue.

`letsencrypt-nginx-proxy-companion` does not allow you to generate wildcard certificates, so `LETSENCRYPT_HOST: *.domain.tld` won't work at all.

See https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319

**Comment by buchdag** [comment]
@sandrodz bump

**Comment by sandrodz** [comment]
@buchdag will test this today, sorry for delay.

**Comment by buchdag** [comment]
@sandrodz did you have the opportunity to test the fix ? This is still hanging.

**Comment by sandrodz** [comment]
Yes, tested it, works as expected.
